### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by Dragnier** [GiantTreeLP/PrettyNiceOres#23]
Looks like something to do with lead, but I don't even have lead in this specific pack as far as I know.

Here is the error report: https://gist.github.com/Dragnier/ee0a3e84fe30df7533de8f571965c719

**Comment by GiantTreeLP** [comment]
`at gtlp.prettyniceores.blocks.modded.NiceLeadOre.getSmeltingResult(NiceLeadOre.java:27)`

Seems like there is no lead ingot in any of the loaded mods. 
Should be an easy fix, though.

**Comment by GiantTreeLP** [comment]
Do you happen to know which app adds the lead ore?

**Comment by GiantTreeLP** [comment]
I'm working on a fix, see the [1.10.2-wip](https://github.com/GiantTreeLP/PrettyNiceOres/tree/1.10.2-wip) branch for changes

**Comment by Dragnier** [comment]
When I added Base Metals to this specific pack (it didn't originally include it), the error went away. Might want to check if the lead entry somehow made the mod dependent on Base Metals.

**Comment by GiantTreeLP** [comment]
The mod fully supports BaseMetals, that's why it works.  
I'm curious about what mod actually adds the lead, because my mod has to load after that mod.  
Otherwise I am unable to get any items from that specific mod.

**Comment by GiantTreeLP** [comment]
What modpack are you using?  
I might check out which mods add ores, to make sure my mod won't break things.

**Comment by Dragnier** [comment]
I believe all of the mods in the pack are listed in that crash report I posted under the system details section except for Optifine. It's just a personal pack I was throwing together. As far as I know, only Forestry adds any ores and that's only Apatite, Copper, and Tin. Here's a list of what was in it when the error happened to me:

```
• JourneyMap (by techbrew)
• Waila (by ProfMobius)
• Waila Harvestability (by squeek502)
• EnderCore (by tterrag1098)
• Ender IO (by CrazyPants_MC)
• Forestry (by SirSengir)
• FTBLib (by FTB)
• FTB Utilities (by FTB)
• Random Things (by lumien231)
• FastLeafDecay (by Olafskii)
• Guide-API (by TehNut)
• Just Enough Items (JEI) (by mezz)
• Roguelike Dungeons (by Greymerk)
• Chisels & Bits (by AlgorithmX2)
• BetterAchievements (by Way2muchnoise)
• Just Enough Resources (JER) (by Way2muchnoise)
• Baubles (by azanor)
• Botania Unofficial (by williewillus)
• Flat Colored Blocks (by AlgorithmX2)
• Quark (by Vazkii)
• Light Level Overlay Reloaded (by oldjunyi)
• MCMultiPart (by amadornes)
• Item Scroller (by masa_)
• Craftable Saddles (by 456Xander)
• Portable Craft Bench (by RenEvo)
• Expandable Backpacks (by Lellson)
• Water Strainer (by Rubironi)
• Roots (by elucent)
• Player Stats (by xMrVizzy)
• Cosmetic Armor Reworked (by ZLainSama)
• Charset (by Vazkii)
• Environmental Creepers (by masa_)
• GraveStone Mod (by EuhDawson)
• Inventory Sorter (by cpw11)
• Cavern (by _kegare)
• Totemic (by ljfa)
• EZStorage 2 (by zero__fall)
• Floocraft (by Hellllp)
• ThutCore (by patnevis)
• Thut's Elevators (by patnevis)
• Chameleon (by jaquadro)
• Storage Drawers (by jaquadro)
• Runes of Wizardry (by xilef11)
• Runes of Wizardry - Classic Dusts Pack (by xilef11)
• Reliquary v1.3 (by P3pp3rF1y)
• Reap Mod (by EuhDawson)
• PrettyNiceOres (by GiantTreeLP)
• RadixCore (by WildBamaBoy)
• Minecraft Comes Alive (by WildBamaBoy)
• BdLib (by bdew)
• Gendustry (by bdew)
• Blood Magic (by WayofTime)
• MineMenu (by dmillerw)
• JustAnotherRottenFleshToLeatherMod (by 456Xander)
• Elements of Power (by gigaherz)
• Agricultural Expansion (by Lionel775)
• Cooking for Blockheads (by Blay09)
• OpenHarvest (by sblectric)
• Mantle (by mDiyo)
• Tinkers Construct (by mDiyo)
```

**Comment by GiantTreeLP** [comment]
Just checked with those mods.  
I was able to recreate the crash (even though no signs of lead are in any of the mods).

Current WIP version is working fine and fixes this crash.  
Update will be out later this day.
