### ISSUE TITLE
Not changing all Substratum Ores

### ISSUE THREAD

**Issue by Dragnier** [GiantTreeLP/PrettyNiceOres#26]
I added PNO to a pack using Substratum instead of Base Metals and it didn't swap out the Copper or Tin. Silver did work, but I haven't checked the rest. Just thought I'd let you know, since Substratum is just like Base Metals and should work with your mod.

![2016-07-16_00 26 15](https://cloud.githubusercontent.com/assets/19270499/16892766/87257d48-4aec-11e6-9cd8-e6eca967bf38.png)

![2016-07-16_00 26 28](https://cloud.githubusercontent.com/assets/19270499/16892767/8725eae4-4aec-11e6-91a6-2fa9b771c1b3.png)

**Comment by GiantTreeLP** [comment]
I found the issue, my world gen only looks at the block, but because all blocks are the same block but with different metadata, it replaces everything with silver (weird though).

**Comment by GiantTreeLP** [comment]
Okay, the fix is done, will be out today (maybe add some ores as well)
